package fitmon;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jas
 */
public class WorkoutDiary extends javax.swing.JFrame {

    private UserSession usrSession;
    /**
     * Creates new form WktDiary
     */
    public WorkoutDiary() {
        initComponents();
    }
    
    public WorkoutDiary(UserSession usrSession) {
        initComponents();
        this.usrSession = usrSession;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diary_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        diary_table = new javax.swing.JScrollPane();
        diary_tab = new javax.swing.JTable();
        ok = new javax.swing.JButton();
        date_diary = new com.toedter.calendar.JDateChooser();
        cancelButton = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        diary_panel.setBackground(new java.awt.Color(255, 255, 255));
        diary_panel.setLayout(null);

        jLabel1.setText("Your Workout Diary For:");
        diary_panel.add(jLabel1);
        jLabel1.setBounds(130, 30, 170, 30);

        diary_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Workout", "Calories Burned", "Intensity", "Duration"
            }
        ));
        diary_table.setViewportView(diary_tab);

        diary_panel.add(diary_table);
        diary_table.setBounds(20, 140, 900, 240);

        ok.setText("Enter");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        diary_panel.add(ok);
        ok.setBounds(480, 40, 59, 23);
        diary_panel.add(date_diary);
        date_diary.setBounds(310, 30, 150, 30);

        cancelButton.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        diary_panel.add(cancelButton);
        cancelButton.setBounds(750, 470, 140, 40);

        img.setBackground(new java.awt.Color(255, 255, 255));
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new.png"))); // NOI18N
        diary_panel.add(img);
        img.setBounds(0, 0, 930, 584);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(diary_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(diary_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)diary_tab.getModel();
        DateFormat df = new SimpleDateFormat("dd MMMM yyyy");
        int userId = usrSession.getUserID();
        String date =  (date_diary.getDate().getYear()+1900+"-"+String.valueOf(date_diary.getDate().getMonth()+1)+"-"+date_diary.getDate().getDate());
        System.out.println(date);
      try{
          Class.forName("com.mysql.jdbc.Driver");
            try (//          /*st = conn.prepareStatement();*/
                    Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/fitmon","root","april-23"); 
                    Statement st = conn.createStatement()) {
                    String query = "SELECT  type, calories, intensity, duration FROM workout where date ='"+date+ "' and userId='"+userId+"';";
                    System.out.println(query);
                        try (
                            ResultSet rs = st.executeQuery(query)) {
                                while(rs.next()){
                                    //Retrieve by column name
                                    //int id  = rs.getInt("id");
                                    String name = rs.getString("type");
                                    System.out.println(name);
                                    double cal = rs.getDouble("calories");
                                    //String date = rs.getString("date");
                                    String intensity = rs.getString("intensity");
                                    int dur = rs.getInt("duration");
                                    model.addRow(new Object[]{name,cal,intensity,dur});

                                    }


                        double total = 0;
                        int column = 1;  // example
                        if (model.getRowCount() == 0){
                          total += (double)model.getValueAt(0, column);
                          model.addRow(new Object[]{"","","",""});
                          model.addRow(new Object[]{"Total Calories Burned:",total});
                        }
                        else{
                            for (int i = 0; i < model.getRowCount(); i++){
                                total += (double)model.getValueAt(i, column);
                                System.out.println(total);// getValueAt(row, column)
                            }
                            model.addRow(new Object[]{"","","",""}); 

                            Object[] row = {"Total Calories Burned:",total};
                            model.addRow(row);
                        }




                    }
            }
          
      }
      catch(ClassNotFoundException | SQLException e){
          JOptionPane.showMessageDialog(this,"Error");
          
      }
        
        
        
        
    }//GEN-LAST:event_okActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkoutDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkoutDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkoutDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkoutDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WorkoutDiary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private com.toedter.calendar.JDateChooser date_diary;
    private javax.swing.JPanel diary_panel;
    private javax.swing.JTable diary_tab;
    private javax.swing.JScrollPane diary_table;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
